### ISSUE TITLE
locking module has problem.

### ISSUE THREAD

**Issue by woshihaoren** [jplana/python-etcd#123]
python: 2.7.5
etcd: 2.2.0

client = etcd.Client()
lock = etcd.Lock(client, 'my_lock_name')
lock.acquire(blocking=True, lock_ttl=None) 

[root@localhost mnt]# python etcd_test.py 
Traceback (most recent call last):
  File "etcd_test.py", line 9, in <module>
    lock.acquire(blocking=True, lock_ttl=None) 
  File "/usr/lib/python2.7/site-packages/etcd/lock.py", line 76, in acquire
    return self._acquired(blocking=blocking, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/etcd/lock.py", line 103, in _acquired
    locker, nearest = self._get_locker()
  File "/usr/lib/python2.7/site-packages/etcd/lock.py", line 175, in _get_locker
    raise etcd.EtcdLockExpired(u"Lock not found")
etcd.EtcdLockExpired: Lock not found

**Comment by lavagetto** [comment]
Ok this is a strange one: I couldn't reproduce this with either etcd 2.1 or etcd 2.0.11, but I can with etcd 2.2.

Probably some api change, I have to dig deeper into it

**Comment by lavagetto** [comment]
I nailed it down.

Quite interestingly, while etcd has always written POST keys in the format
   /_locks/my_lock_name/7

in etcd 2.2 it now writes

  /_locks/my_lock_name/00000000000000000007

which of course kills our module.

I will think of a non-butt-ugly fix, thanks for reporting this

**Comment by woshihaoren** [comment]
client = etcd.Client()
lock = etcd.Lock(client, 'my_lock_name')
lock.acquire(blocking=False, lock_ttl=60)
lock.is_acquired()

[root@localhost /]# python etcd_test.py 
Traceback (most recent call last):
  File "etcd_test.py", line 9, in <module>
    lock.is_acquired()  
TypeError: 'bool' object is not callable 

this is_acquired has problem~

**Comment by ustcyue** [comment]
May I know is this fix released? why I am still getting this exact same error when using python-etcd 0.4.5 with etcd 2.2.0

**Comment by adithya66** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 322, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 598, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/site-packages/celery/worker/loops.py", line 145, in synloop
    connection.drain_events(timeout=2.0)
  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 301, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 961, in drain_events
    get(self._deliver, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/scheduling.py", line 56, in get
    return self.fun(resource, callback, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 999, in _drain_channel
    return channel.drain_events(callback=callback, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 745, in drain_events
    return self._poll(self.cycle, callback, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 402, in _poll
    return cycle.get(callback)
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/scheduling.py", line 56, in get
    return self.fun(resource, callback, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 405, in _get_and_deliver
    message = self._get(queue)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/etcd.py", line 153, in _get
    with self._queue_lock(queue):
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/etcd.py", line 82, in _queue_lock
    lock.acquire(blocking=True, lock_ttl=self.lock_ttl)
  File "/usr/local/lib/python2.7/site-packages/etcd/lock.py", line 76, in acquire
    return self._acquired(blocking=blocking, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/etcd/lock.py", line 103, in _acquired
    locker, nearest = self._get_locker()
  File "/usr/local/lib/python2.7/site-packages/etcd/lock.py", line 175, in _get_locker
    raise etcd.EtcdLockExpired(u"Lock not found")
EtcdLockExpired: Lock not found


I am still getting this error.
python-etcd==0.4.3
