### ISSUE TITLE
PyPi package seems to be broken

### ISSUE THREAD

**Issue by mikroskeem** [jplana/python-etcd#185]
```
Collecting etcd
  Downloading etcd-2.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0qk1vtr6/etcd/setup.py", line 13, in <module>
        with open(os.path.join(app_path, 'resources', 'requirements.txt')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-0qk1vtr6/etcd/etcd/resources/requirements.txt'
```

Installing works fine by issuing `pip install git+https://github.com/jplana/python-etcd`

**Comment by mikroskeem** [comment]
Whoops, it's `python-etcd` not `etcd`, didn't notice my mistake.

**Comment by yoursweetie** [comment]
I downloaded etcd-2.0.0.tar.gz and built it from source, came across the same problem:
``` 
> python setup.py install
raceback (most recent call last):
  File "setup.py", line 13, in <module>
    with open(os.path.join(app_path, 'resources', 'requirements.txt')) as f:
IOError: [Errno 2] No such file or directory: '/xxx/etcd-2.0.8/etcd/resources/requirements.txt'
```
any suggestions?
Thanks!
