### ISSUE TITLE
TLS "hostname doesn't match exception"

### ISSUE THREAD

**Issue by ae6rt** [jplana/python-etcd#187]
Hello, and thank you for python-etcd.  When I run this code

```
import etcd

if __name__ == "__main__":
    c = etcd.Client(host="10.2.23.10", port=2379, protocol="https", ca_cert="cacert.pem") 
    c.api_execute("/version", 'GET').data
```

against a server bearing this certificate

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            7f:ff:bc:cf:b7:c6:dc:a3:3e:4c:76:79:c8:6d:56:3c:54:23:ee:a0
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=Xoom, OU=INF ENG, L=San Francisco, ST=California, CN=Xoom INF ENG CA
        Validity
            Not Before: Jul  6 00:28:00 2016 GMT
            Not After : Jul  4 00:28:00 2026 GMT
        Subject: C=US, ST=California, L=San Francicso, O=INF ENG, OU=etcd cluster, CN=etcd
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:df:94:2b:6f:4d:f2:e0:97:2d:55:18:f7:a0:10:
                    90:6d:f9:3f:35:03:2f:f1:f8:b8:ad:5e:96:64:f3:
                    f3:1e:30:e1:12:27:72:c6:79:11:b9:68:44:35:19:
                    f0:db:f9:f6:15:a9:eb:92:0c:44:cb:c7:fd:19:dd:
                    a2:c5:9c:10:77:81:e3:54:ea:6f:7d:86:ff:f4:86:
                    b0:13:cb:7d:9f:78:7e:28:6f:3f:45:ca:4d:bb:90:
                    20:00:db:8d:4e:8c:6c:33:de:0f:48:82:47:ec:0d:
                    9b:e9:88:45:3f:c0:2d:86:6a:9d:c3:62:fa:7f:d8:
                    c4:35:5b:36:84:6c:c3:a2:bb:4a:8a:76:cc:6d:f6:
                    92:1a:f6:d1:0a:58:f1:49:14:05:5f:63:78:6f:87:
                    94:20:e8:03:f5:9a:9a:e1:5c:dd:0e:34:98:15:1c:
                    c5:af:24:9e:d1:49:2f:40:72:ce:eb:84:b3:3f:bc:
                    38:3e:94:ee:06:88:78:5b:9a:c3:8c:95:74:66:e6:
                    14:ab:ce:89:7b:c7:cf:ff:3d:47:0b:5b:ad:88:a0:
                    23:78:9d:94:8a:4e:cc:c6:4e:c4:46:d4:de:52:d7:
                    83:5d:07:4e:ea:14:d2:9a:02:c9:d9:24:87:9d:1a:
                    91:2b:89:20:ab:a7:6f:58:61:1e:b6:26:5a:b6:eb:
                    60:77
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier: 
                FD:30:A8:DF:EB:6A:67:30:63:C6:69:65:D0:65:48:85:94:7E:09:D0
            X509v3 Authority Key Identifier: 
                keyid:84:1C:C5:89:42:DC:E2:FF:96:15:65:28:D2:A2:17:BD:D1:E6:D5:0C

            X509v3 Subject Alternative Name: 
                DNS:localhost, IP Address:127.0.0.1, IP Address:10.2.23.10, IP Address:10.2.23.11, IP Address:10.2.23.9
    Signature Algorithm: sha256WithRSAEncryption
         75:97:75:40:5d:5f:8b:41:82:ac:94:29:b6:0e:b8:7a:22:43:
         21:2b:a3:20:e4:56:0e:94:5a:b0:2a:76:81:9f:ee:10:fc:b7:
         9d:f0:91:2a:a2:ef:61:65:45:4f:9e:22:3c:9d:00:81:49:bb:
         86:5c:3a:5c:8d:68:25:9a:f4:2a:4c:e9:f8:4a:b7:75:b6:49:
         dc:69:37:d0:72:99:bc:df:b3:18:be:13:39:7b:0f:88:23:70:
         1a:30:8f:30:78:a2:a9:1e:b6:a3:15:12:af:ff:78:e1:b6:18:
         32:a9:99:de:ae:c8:c6:9c:49:c1:1d:0e:4b:33:ef:b6:1d:e6:
         71:52:c0:8a:0a:57:2e:c1:ec:43:18:2a:d5:ee:8f:32:5e:01:
         5c:4b:74:0b:4a:05:96:32:d0:80:cc:50:20:af:8a:b4:69:bc:
         39:8c:6e:c1:6a:28:71:be:ba:12:e9:3d:5a:fc:8c:65:0b:0f:
         a8:ba:0c:9f:52:ab:a4:25:79:92:ab:bb:de:24:ee:b8:1f:a1:
         d9:88:60:bd:26:6d:80:10:db:5c:e9:4a:c1:2e:03:5b:f4:28:
         3a:58:a5:fd:14:ed:34:b5:82:8e:4d:54:24:17:d3:af:3b:54:
         a3:cd:09:ba:e4:be:09:21:ba:9d:6b:0d:a7:b9:73:3f:cf:42:
         bc:21:11:03
```

I receive

```
$ python main.py 
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    c.api_execute("/version", 'GET').data
  File "/Library/Python/2.7/site-packages/python_etcd-0.4.3-py2.7.egg/etcd/client.py", line 857, in wrapper
    cause=e
etcd.EtcdConnectionFailed: Connection to etcd failed due to SSLError(CertificateError("hostname '10.2.23.10' doesn't match 'localhost'",),)
```

I am using python 2.7.10.  It appears to me that client or its dependencies is not availing itself of the Subject Alternative Names in the cert, but I could be wrong.  Do I need to install additional python packages in support of python-etcd to avoid this error? 

Thank you.

**Comment by ae6rt** [comment]
I bet this is the problem:

https://github.com/shazow/urllib3/issues/258

**Comment by lavagetto** [comment]
Should be solved with my patch to use a more modern urllib3
