### ISSUE TITLE
Memebers latency

### ISSUE THREAD

**Issue by aafanasyev** [jplana/python-etcd#188]
Hi *,

Can I get somehow a latency information about nodes?

AFAIK it is part of statistics, but I cannot find how I can get it in python-etcd.

regards

**Comment by aafanasyev** [comment]
Sorry. I have found this:
```
import etcd

if __name__ == "__main__":
    client = etcd.Client(host='192.168.1.100', port=2379)
    print(client.leader_stats)
```

But I am getting such error:

Traceback (most recent call last):
  File "C:/Users/andre/PycharmProjects/LE/core/Collection.py", line 10, in <module>
    print(client.leader_stats)
  File "C:\Python34\lib\site-packages\etcd\client.py", line 356, in leader_stats
    return self._stats('leader')
  File "C:\Python34\lib\site-packages\etcd\client.py", line 369, in _stats
    + '/stats/' + what, self._MGET).data.decode('utf-8')
  File "C:\Python34\lib\site-packages\etcd\client.py", line 848, in wrapper
    return self._handle_server_response(response)
  File "C:\Python34\lib\site-packages\etcd\client.py", line 928, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "C:\Python34\lib\site-packages\etcd\__init__.py", line 304, in handle
    raise exc(msg, payload)
etcd.EtcdException: not current leader : None

how to solve it?

**Comment by aafanasyev** [comment]
Solved.

A client need to be connected to a leader to get statistics. In my situation all nodes are behind nat and connection from local machine to nodes is done via a port that is port of member not a leader.
