### ISSUE TITLE
TypeError when quitting with sys.Exit()

### ISSUE THREAD

**Issue by lstep** [jplana/python-etcd#190]
When running this simple program:
```python
import etcd
import sys

if __name__ == "__main__":
    client = etcd.Client(port=2379)
    sys.exit()

```

I get an error when exiting. Other functions (read()) work fine:
```
Exception ignored in: <bound method Client.__del__ of <etcd.client.Client object at 0x7ff7739bae48>>
Traceback (most recent call last):
  File "/tmp/ETCD/lib/python3.4/site-packages/python_etcd-0.4.3-py3.4.egg/etcd/client.py", line 226, in __del__
  File "/tmp/ETCD/lib/python3.4/site-packages/urllib3-1.16-py3.4.egg/urllib3/poolmanager.py", line 160, in clear
  File "/tmp/ETCD/lib/python3.4/site-packages/urllib3-1.16-py3.4.egg/urllib3/_collections.py", line 89, in clear
TypeError: 'NoneType' object is not callable
```

I'm using the current version of python-etcd from the repository (0.4.3) with etcd 3.0.3 and python 3.4.3.

**Comment by lavagetto** [comment]
This looks like a problem in urllib3's poolmanager. I'll take a look later.

**Comment by cenkalti** [comment]
Duplicate of #179
