### ISSUE TITLE
Unable to write or read

### ISSUE THREAD

**Issue by manishshambu** [jplana/python-etcd#259]
I have the etcd server up and running. I have etcd client installed. However I'm unable to write or read from the server. I'm not even able to query the machines (client.machines).

Am I missing something?

Traceback (most recent call last):
  File "/Users/manishshambu/DistributedSystems/Raft/src/abc.py", line 6, in <module>
    client.write('/nodes/n2', 2, ttl=4)
  File "/usr/local/lib/python3.6/site-packages/etcd/client.py", line 500, in write
    response = self.api_execute(path, method, params=params)
  File "/usr/local/lib/python3.6/site-packages/etcd/client.py", line 907, in wrapper
    return self._handle_server_response(response)
  File "/usr/local/lib/python3.6/site-packages/etcd/client.py", line 987, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/usr/local/lib/python3.6/site-packages/etcd/__init__.py", line 306, in handle
    raise exc(msg, payload)
etcd.EtcdException: Bad response : 404 page not found

**Comment by VladimirBalun** [comment]
What was the problem?
