### ISSUE TITLE
Cannot import etcd even I have installed python-etcd on my computer.

### ISSUE THREAD

**Issue by HoLo-Debris** [jplana/python-etcd#278]
I have install `python-etcd 0.4.5` on my computer, but when I import this module, the error showed up.

+ python: `3.7.9`
+ python-etcd: `0.4.5`
+ system: `openEuler 20.03 (LTS-SP1)`
+ architecture: `x86_64`  
When I import etcd in the python3 interactive interface, I got the error:  

>import etcd
  Traceback (most recent call last) :  
  File "<stdin>", line 1, in <module>  
  File "/usr/local/lib/python3.7/site-packages/python etcd-0.4.5-py3.7.egg/etcd/ init.py", line 2, in \<module\>  
  &emsp;&emsp;from .client import Client  
  File "/usr/local/lib/python3.7/site-packages/python_etcd-0.4.5-py3.7.egg/etcd/client.py",line21,in \<module\>  
    &emsp;&emsp;import ssl   
  File "/usr/lib64/pvthon3.7/ssl.py", line 98, in <module>  
    &emsp;&emsp;import _ssl                      # if we can't import it, let the error propagate
ImportError: /usr/lib64/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so: symbol SSLv3_method version OPENSSL_1_1_0 not defined in file libssl.so.1.1 with link time reference

Here is the screenshort that may help you to get more about the problem :
![image](https://user-images.githubusercontent.com/34963138/147078347-358ff953-be21-448b-97f4-2ed350cbb0c8.png)

**Comment by HoLo-Debris** [comment]
The problem with `symbol SSLv3_method version OPENSSL_1_1_0 not defined in file libssl.so.1.1 with link time reference` seems to be common on arch, I met a lot like that on arch linux. Referencing [here](https://bbs.huaweicloud.com/forum/forum.php?mod=viewthread&tid=100729) I solved it once.  [Here](https://github.com/dotnet/runtime/issues/19895#issuecomment-293008002) might help, too.
