### ISSUE TITLE
client hangs on write 

### ISSUE THREAD

**Issue by veverjak** [jplana/python-etcd#75]
Hi, 

I have trouble when writing data to etcd although I can read data without any problem. Would anyone know where the problem could be? 

I have following simple code: 
```
#!/usr/bin/python
import etcd
                                                                                                                                                                   client = etcd.Client(host = '127.0.0.1', port = 5000)

print client.read('/coreos_apps/marathon/dev')
print client.write('/writetest', 'TESTSTRING')
```

Here is my output after I interrupt program with ctrl+C
```
-> % python scripts/etcd_test.py<class 'etcd.EtcdResult'>({'newKey': False, 'raft_index': 64071, '_children': [], 'createdIndex': 6684, 'modifiedIndex': 6684, 'value': u'{"ssh_port": 224, "count": 1, "version": "latest", "ssh_support": true}', 'etcd_index': 16626, 'expiration': None, 'key': u'/coreos_apps/marathon/dev', 'ttl': None, 'action': u'get', 'dir': False})




^CTraceback (most recent call last):
  File "scripts/etcd_test.py", line 9, in <module>
    print client.write('/writetest', 'TESTSTRING')
  File "/usr/lib/python2.7/site-packages/python_etcd-0.3.2-py2.7.egg/etcd/client.py", line 272, in write
    response = self.api_execute(path, method, params=params)
  File "/usr/lib/python2.7/site-packages/python_etcd-0.3.2-py2.7.egg/etcd/client.py", line 575, in api_execute
    redirect=self.allow_redirect)
  File "build/bdist.linux-x86_64/egg/urllib3/request.py", line 135, in request_encode_body
  File "build/bdist.linux-x86_64/egg/urllib3/poolmanager.py", line 174, in urlopen
  File "build/bdist.linux-x86_64/egg/urllib3/poolmanager.py", line 153, in urlopen
  File "build/bdist.linux-x86_64/egg/urllib3/connectionpool.py", line 516, in urlopen
  File "build/bdist.linux-x86_64/egg/urllib3/connectionpool.py", line 308, in _make_request
  File "/usr/lib64/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 791, in send
    self.connect()
  File "build/bdist.linux-x86_64/egg/urllib3/connection.py", line 154, in connect
  File "build/bdist.linux-x86_64/egg/urllib3/connection.py", line 133, in _new_conn
  File "build/bdist.linux-x86_64/egg/urllib3/util/connection.py", line 78, in create_connection
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
```

Every time it seems it hangs here: 
```
  File "/usr/lib/python2.7/site-packages/python_etcd-0.3.2-py2.7.egg/etcd/client.py", line 272, in write
    response = self.api_execute(path, method, params=params)
```

Could it be due to connection problem? Weird is that Read works without any problem.

I have no problems writing to database using curl.

My Setup:
python --version
Python 2.7.5

etcd version 0.4.6

Would you need any info for debugging ?

**Comment by cameronmaske** [comment]
I have the same problem. 
I think it has something to do with etcd 0.4.6 returning a [307](https://github.com/coreos/etcd/issues/673) (HTTP/1.1 307 Temporary Redirect) and urllib3 not following that on a PUT request.

**Comment by veverjak** [comment]
Nope, it was called from docker container running on CoreOS host. 
I was connecting to etcd running on CoreOS.

**Comment by lavagetto** [comment]
The library is tested with 0.4.6 and failure to write while you can still read means your etcd cluster has lost quorum, most probably.
